# Generated by Django 5.0.2 on 2024-03-05 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_postcomment_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='parent',
        ),
    ]
